grpc:
  client:
    hostname: yz
    port: 8443
    ssl:
      enabled: true
      key-cert-chain: client.crt
      key: client.pk8
      trust-manager: ca.crt
      client-auth: REQUIRE
      ssl-provider: OPENSSL

    worker:
      n-threads: 15
      pool-name: grpc-worker-group
    direct-executor: true
    interceptors:
      - yz.grpc.client.common.interceptor.LoggingInterceptor
      - yz.grpc.client.common.interceptor.SessionInterceptor