grpc:
  client:
    hostname: 127.0.0.1
    port: 2018
    worker:
      n-threads: 15
      pool-name: grpc-worker-group
    direct-executor: true
    interceptors:
      - yz.grpc.client.common.interceptor.LoggingInterceptor
      - yz.grpc.client.common.interceptor.SessionInterceptor